const globe = document.querySelector("#tortoise");
const button = document.querySelector("#press");
const message = document.querySelector("#message");

const messages = [
  "In 1996, the Concorde set the record flying time from New York to London- making the journey in only 2 hours, 52 minutes, and 59 seconds and traveling at speeds of up to 1,354 mph.",
  "The Concorde was retired in 2003.",
  "The Boeing 747 has roughly 6 million parts.",
  "Although 80% of people have a fear of flying (aerophobia) only 5% of the world’s population have been on an airplane.",
  "There are an average of 10,000 planes in the sky at any one time carrying roughly 1 million passengers.",
  "The first African American woman to earn a pilot’s license was Willa Brown in 1939.",
  "The pilot and co-pilot on a flight are not allowed to eat the same meal.",
  "On average, each commercial airplane is struck by lightning at least once a year. (Dw, planes are built to handle that)",
  "The average cruising speed of a commercial jet is around 575 mph (925 km/h), which is about 75% of the speed of sound.",
  "Most commercial airplanes are painted white to reflect sunlight, which helps keep the aircraft cooler and minimizes potential sun damage to the fuselage.",
  "Commercial airplanes typically fly at altitudes between 30,000 and 40,000 feet. This is nearly 6 to 8 miles above the Earth’s surface!",
  "The oxygen masks that drop down in case of cabin pressure loss provide only about 12 to 15 minutes of oxygen.",
  "Have you ever noticed the small hole at the bottom of airplane windows? It’s called a breather hole and it’s there to regulate air pressure between the inner and outer window panes.",
  "If you're a LEGO fan, you'll love this fact! While the largest LEGO set consists of over 11,000 pieces, the Boeing 787 Dreamliner is made up of 2.5 million parts—each one catalogued and meticulously assembled.",
  "747s have flown more than 3.5 billion people.",
  "At any given moment, there are about 61,000 people airborne over the mainland United States. At Chicago-O’Hare Airport, one of the world’s busiest, planes take off or land every 37 seconds. More than 29,000 flights operate from the U.S. alone every day.",
  "Aircraft control towers need to have constant visibility of the airfield at all times. To that end, the glass in tower windows is angled precisely at 15°, which prevents glare and reflections from blocking a controller’s view of the runways.",
  "According to one estimate, you can lose about two cups of water from your body for every hour you spend flying—most of it breathed out through the mouth.",
  "Planes Can Glide Without Engines.",
  "Dimming cabin lights during takeoff and landing is a safety measure. It helps passengers’ eyes adjust to low-light conditions, preparing them for quick evacuation in case of an emergency.",
  "Despite the ban on smoking aboard most flights, airplane lavatories are still equipped with ashtrays. This might seem outdated, but it’s a necessary precaution. If someone violates the no-smoking policy, the ashtray provides a safe place to extinguish cigarettes, reducing fire hazards.",
  "Contrails, the white streaks left by airplanes, form when hot exhaust gases from jet engines mix with the cold atmosphere at high altitudes. This condensation process results in water vapor freezing into tiny ice crystals, creating visible trails.",
  "Your taste buds do not work the same way at 35,000 feet; low cabin humidity and pressurized air can reduce your senses of sweet and salty flavors by almost 30%. Airlines counter it by making their meals way more seasoned and umami-rich. (That's why the food tastes weird)",
  "The air inside airplane cabins has humidity levels as low as 10-20%, compared to 30-50% on the ground. This dryness can cause dehydration, skin irritation, and discomfort during long flights.",
  "Tray tables are among the dirtiest surfaces on an airplane, harboring more bacteria than lavatory surfaces. Passengers often use them for eating, working, and resting personal items, but they’re not always sanitized between flights.",
  "Among all the facts about aviation, the Antonov An-225 Mriya, the world’s largest aircraft, weighs 600 tons and was built to transport oversized cargo. Its massive size and engineering brilliance make it a marvel in the aviation industry.",
  "Studies show that passengers seated at the back of an airplane have higher survival rates in emergencies. ",
  "Pointing lasers at aircraft is illegal because it can temporarily blind or distract pilots, especially during critical phases like takeoff and landing.",
  "Flights are overbooked to keep fares low.",
  "Flight attendants have a variety of roles.",
  "Flight attendants are paid once the plane doors close",
  "Cabin air may be bad for your health.",
  "Air pressure makes your legs swell",
  "Pilots often fall asleep on the job.",
  "Budget airlines aren't less safe than full service carriers.",
  "Your lost luggage gets auctioned off.",
  "Air on top of the wings creates lift, not the air below.",
  "If your phone's left on, it probably won't interfere with the equipment (please still turn on airplane mode).",
  "Meals are prepared on the ground a few days in advance.",
  "Good manners goes a long way.",
  "Planes can really fly and land themselves.",
  "The world's shortest flight is just one minute long.",
  "Carbon from planes stays in the atmosphere for 100 years.",
  "That blanket and pillow are safety features too.",
  "Flight attendants have to be strong swimmers.",
  "A plane can't take off if you're in the loo.",
  "Airports collect extortionate landing fees.",
  "Eager to get on board? Cabin crew have a name for you (it's gate lice btw)",
  "The pilots and cabin crew rest in hidden compartments",
  "Planes are unlikely to crash due to turbulence.",
  "Empty 'ghost flights' fly all the time.",
  "Fly in the morning for less turbulence.",
  "Cabin pressurization was invented during WWII",
  "Aircraft Can Safely Fly Even When One Engine Fails",
  "The Wright brothers invented and flew the first airplane in 1903.",
  "The world’s smallest jet is the BD-5 Micro. Its wingspan is 14–21 feet and weighs just 358 pounds.",
  "The average Boeing 747 has around 150–175 miles of wiring inside it.",
  "There have been more astronauts than pilots who have flown the Concorde.",
  "The first woman in the U.S. to become licensed to fly a play was Harriet Quimby.",
  "Commercial airport runways are typically 2 to 4 feet thick with layers of asphalt. Taxiways are usually thinner, with around 18 inches of concrete.",
  "Airplanes typically fly at an altitude of around 35,000 feet. If Earth were the size of a desktop globe, a plane at that height would be flying at only 1/10 of an inch off the surface.",
  "The world’s largest passenger plane is the Airbus A380. It is a double-decker four-engine jetliner. It made its first flight on April 27, 2005.",
  "The Antonov AN-225 cargo jet is the largest plane in the world. It is nearly as big as a football field from nose to tail and wingtip to wingtip. It was originally built to transport a space plane.",
  "Approximately 95.7% of those involved in a plane crash survive it.",
  "The amount of fuel that a Boeing 767-400 carries is enough to fill 1,400 minivans.",
  "The world’s busiest airport is the Hartsfield-Jackson Atlanta International Airport. Dubai International and Tokoyo Intl (Haneda) round out the top three.",
  "he risk of being killed in a plane crash for the average American is 1 in 11 million. The risk of being killed in a car accident is 1 in 5,000.",
  "Mercury is not allowed on a flight. Even a small amount of mercury can seriously damage aluminum, which is what most planes are made from. Airplanes that are exposed to mercury are usually quarantined.",
  "Research shows that the first 3 minutes after takeoff and the final 8 minutes before landing are when 80% of plane crashes happen.",
  "About 25 million Americans people have some of fear flying, or “aviophobia.”",
  "In 1987, American Airlines saved $40,000 by removing 1 olive from each salad served in first class.",
  "Often dubbed the “Father of Aviation,” in 1799 English aviator George Cayley (1773–1857) built the first glider that could go short distances.",
  "The FAA requires that all airplanes be capable of being evacuated in 90 seconds. It takes only a minute and half for a fire to spread and engulf a plane.",
  "Research indicates, that people fall in love with flight attendants at first sight more than any other professions.",
  "If a cabin is pressurized and an airplane door came open in midflight at a high altitude, the sudden opening could cause items and people to get sucked out. However, pressurization in the cabin and a plug-type door (a door that is bigger than the opening), makes it near impossible for even multiple people to open a door during a flight.",
  "Passenger airplanes are notorious germ hotbeds.",
  "In 1947, Chuck Yeager became the first person to fly faster than the speed of sound.",
  "Climate change and warmer air is increasing clear-air turbulence for airplanes. Not only does increased turvulence create more wear-and-tear- on an airplanes, pilots also burn more fuel to try to avoid it.",
  "Between June 14 and 15, 1919, British airmen John Alcock and Arthur Brown made the first nonstop flight across the Atlantic Ocean.",
  "In 1986, a plane called Voyager flew all the way around the world without landing or refueling.",
  "The world’s first fatal airplane crash occurred in 1908.",
  "In 1938 Howard Hughes filled his plane with ping-pong balls so it would float if it went down over the ocean.",
  "The first airplane toilets were simply a hole in the plane’s fuselage through which one could see the countryside passing below.",
  "The majority of commercial pilots are paid for the number of hours they fly and not on a monthly basis.",
  "The place near the tail of an airplane is the safest to be in the event of a crash.",
  "The world’s largest runway is in China at the ‘Qamba Bamba’ Airport. It is 5.5. Kilometers in length.",
  "Airplane manufacturers do not manufacture all the parts themselves. They depend on hundreds of suppliers to provide them with parts including seats, fuselages, and engines, etc.",
  "The Concorde flew faster at 50,000 to 55,000 feet. At this height, air turbulence was less of a problem, and the travelers could see the curvature of the Earth from the plane.",
  "A total of 20 Concordes were built. 14 of these flew commercially both for British Airways and Air France.",
  "All international airline pilots speak English, which is a prerequisite.",
  "In some cases, the pilot can dump fuel in order to make an emergency landing. This is done to avoid the excessive weight of the aircraft while landing at places where suitable conditions might not exist. The dumped fuel, however, evaporates and does not reach the ground.",
  "A Boeing 747 aircraft held the passenger capacity record for 37 years.",
  "If the distance covered by the entire fleet of Boeing 747s is added up, you could make 75,000 trips to the moon and back.",
  "The world’s longest non-stop flight is 18 hours and 50 minutes from Singapore (SIN) to New York City (JFK) serviced by Singapore Airlines.",
  "Almost 30,000 flights take place in the U.S. every day. And more than two million passengers travel via aircraft every 24 hours.",
  "Established in 1919, KLM is the world’s oldest airline, while Quantas is the world’s second oldest.",
  "Out of the total number of airports in the world, one-third are located in the U.S.",
  "In 1999, Alaska Airlines introduced the online check-in option for the first time.",
  "Are you interested in learning how airplanes fly? As the airplane flies, the air pressure below and above the wings is different. The difference in the pressure keeps the airplane airborne. Technically, this difference of pressure is termed as “lift.”",
  "Airplanes are an American invention.",
  "In 1920s and 1930s, pilots were given “Blunder Trophies” for making silly mistakes while operating airplanes.",
  "The fate of a Boeing 727 that took off in 2003 is still unknown.",
  "The North Maeric X-15 is the fastest supersonic airplane. It can fly at a speed of 6.7 Mach (7,200 km/h). In other words, it can fly at 6.7 times the speed of sound.",
  "Some airports can be bigger than the size of an entire country. King Fahd International Airport in Dammam, Saudi Arabia sits on 192,000 acres of land—that’s bigger than the entire country of Bahrain.",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];

button.addEventListener("click", () => {
  globe.classList.add("shaking");
  setTimeout(() => globe.classList.remove("shaking"), 600);

const pick = Math.floor(Math.random() * messages.length);
  message.textContent = messages[pick];
});